#! /bin/bash

#
# ins utilities
#

install() {
    yay -Q "${1}" &>/dev/null || yay -S "${1}"
}

create_dir() {
	[ ! -d "${1}" ] && mkdir "${1}"
}

sudo_create_dir() {
	[ ! -d "${1}" ] && sudo mkdir "${1}"
}

backup_file() {
	if [ -f "${1}" ] && [ ! -L "${1}" ]; then
		mkdir -p "${PWD}/backups/$(dirname ${1})"
		mv "${1}" "${PWD}/backups/$(dirname ${1})/$(basename ${1}).$(date +%s)"
		rm "${1}"
	fi

	if [ -f "${1}" ] && [ -L "${1}" ]; then
		unlink "${1}"
	fi
}

backup_dir() {
  if [ -d "${1}" ] && [ ! -L "${1}" ]; then
    mkdir -p "${PWD}/backups/$(dirname ${1})"
    mv "${1}" "${PWD}/backups/$(dirname ${1})/$(basename ${1}).$(date +%s)"
  fi

  if [ -d "${1}" ] && [ -L "${1}" ]; then
    unlink "${1}"
  fi
}

sudo_backup_file() {
	if [ -f "${1}" ] && [ ! -L "${1}" ]; then
		mkdir -p "${PWD}/backups/$(dirname ${1})"
		sudo mv "${1}" "${PWD}/backups/$(dirname ${1})/$(basename ${1}).$(date +%s)"
		sudo rm "${1}"
	fi

	if [ -f "${1}" ] && [ -L "${1}" ]; then
		sudo unlink "${1}"
	fi
}

#
# System
#

install "greetd-tuigreet"
sudo_create_dir "/etc/greetd"
sudo_backup_file "/etc/greetd/config.toml"
sudo ln -s ${PWD}/etc/greetd/config.toml /etc/greetd/config.toml

install "tofi"
backup_dir "${HOME}/.config/tofi"
ln -s "${PWD}/home/${USER}/.config/tofi" "${HOME}/.config/tofi"

install "brightnessctl"

#
# Terminal
#

install "kitty"
backup_dir "${HOME}/.config/kitty"
ln -s "${PWD}/home/${USER}/.config/kitty" "${HOME}/.config/kitty"

install "nvim"
backup_dir "${HOME}/.config/nvim"
ln -s "${PWD}/home/${USER}/.config/nvim" "${HOME}/.config/nvim"

#
# Desktop application
#

install "steam"
install "spotify"
install "librewolf-bin"
install "telegram-desktop"
install "vlc vlc-plugins-all"

# yay -S hyprland
# # ~/.config/hypr/hyprland.conf
#
# yay -S hyprpaper
# # ~/.config/tofi/config
#

#
# Terminal
#
#
# yay -S otf-hasklig-nerd
#
#
# yay -S fish
# # copy configuration file
#
# yay -S starship
# # copy configuration file
#
# yay -S tmux python-libtmux
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# # copy configuration file
#
# yay -S nvim
# # copy configuration file
